version: '3.8'

services:
  discord-bot:
    build:
      context: .
    container_name: discord-bot
    volumes:
      - .:/app
    command: ["node", "index.js"]
    environment:
      - NODE_ENV=development
      - LISTENER_CLIENT_ID=${LISTENER_CLIENT_ID}
      - LISTENER_TOKEN=${LISTENER_TOKEN}
      - SPEAKER_CLIENT_ID=${SPEAKER_CLIENT_ID}
      - SPEAKER_TOKEN=${SPEAKER_TOKEN}
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
